# Generated by Django 5.1.4 on 2025-05-06 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('DEBIT', 'Debit Card'), ('CREDIT', 'Credit Card')], max_length=10)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LOST', 'Lost'), ('STOLEN', 'Stolen'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=10000.0, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.account')),
            ],
        ),
    ]
